doc: workflow should not trigger on own comments
zeebe-io/backport-action pull request #244
Opened 2022-06-02 11:35 UTC by remcowesterhoud

The backport-action bot added comments to PRs contain "/backport". This could result in the backport workflow being triggered again, causing an infinite loop of backport messages. By checking the user id of the comment we can prevent comments from backport-action triggering the workflow.

2022-06-02 11:36 UTC, remcowesterhoud commented
Let me know if you'd rather have the check be `github.event.comment.user.login != "backport-action"` instead.

2022-06-22 12:46 UTC, korthout reviewed
Interesting point. So this PR had `/backport` in the title or in the branch? So once the new PR was opened, the bot user commented on the original PR and the workflow ran once more. Do I have that right?

This example uses the default `GITHUB_TOKEN` as the `github_token` so the `github-action` user opens the PR. I'm not sure what the id of that user is. In any case, the user depends on the defined value of the `github_token` option, which makes this more complex. 

I'm not sure we should complicate this example even further. It's already rather confusing IMO. I'd rather push for replacing the issue_comment section with a dedicated action like https://github.com/peter-evans/slash-command-dispatch. This dispatching will have the added benefit that the backport-action itself is not triggered for every comment, cleaning up the Actions overview.

WDYT?

2022-06-22 13:09 UTC, korthout requested changes
You've convinced me that this doc can be an easy win. 

However, I believe we should look towards better slash command handling using a dedicated action in the future.

Thanks for your proposal. Please consider these suggestions to clarify things in more detail.

2022-06-22 13:09 UTC, korthout commented on README.md
> +        github.event.commend.user.id != 97796249 &&
```suggestion
        github.event.comment.user.id != 97796249 &&
```

2022-06-22 13:09 UTC, korthout commented on README.md
> +    # bot user (user id: 97796249)
```suggestion
    # or when a comment containing `/backport` is created by someone other than the 
    # https://github.com/backport-action bot user (user id: 97796249). Note that if you use your
    # own PAT as `github_token`, that you should replace this id with yours.
```

2022-06-22 13:16 UTC, korthout approved these changes
Thanks @remcowesterhoud LGTM 📘

2022-06-22 13:17 UTC, merged